title: "최효주의 워홀 일지"
baseurl: "/journal"
url: "https://hjchoi9807.github.io"

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - _pages/checklist.md
  - _pages/resources.md
